### ISSUE TITLE
Issue using fish/zsh shell instead of bash

### ISSUE THREAD

**Issue by vincentjames501** [nerdyjem/apkmanager#1]
First I'd like to say this is an awesome utility and works incredibly well.  I recently switched my default shell to fish and it would be awesome if this tool supported it.  I think the only thing that needs to be changed is this:

in APKManager.scpt

before do script "if [ $(command -v apkm) ]; then apkm; else \"" & mainDir & "/other/main.sh\"; fi; exit" in newTab

simply run 'do script "bash" in newTab" before to change the new terminal to use bash instead

**Comment by nerdyjem** [comment]
Hi and I'm sorry for not responding to this sooner.

I use ZSH as my login shell on OSX 10.9 and have no problems at all. The user's default shell shouldn't matter at all, since the script's are all coded for /bin/sh

Regardless, I've pushed a change to the develop branch that includes this fix, and I've updated the AppleScript source page on the wiki.
