### ISSUE TITLE
How do I create a new project?

### ISSUE THREAD

**Issue by hex** [nerdyjem/apkmanager#3]
I can't see anywhere in the wiki what a "project" is and how do you create one. 

Thanks.

**Comment by nerdyjem** [comment]
Sorry if this is confusing, but "projects" were just a list of apk files found in the projects directory... I think at least; it's been a few years since I've looked at any of the code in this script. I'd be surprised if this even works anymore, and I'm sure other (newer) tools are better for de-compiling/re-engineering android apk files now.
